### ISSUE TITLE
Unexpected results with standardIntonation

### ISSUE THREAD

**Issue by hanshoglund** [music-suite/music-pitch#43]
Possibly related to overloading of vector-space operators on Hertz/FreqRatio.

```hs
>>> fmap standardIntonation [a,a']
[Hertz {getHertz = 441.0},Hertz {getHertz = 441.0}]
-- Expected: 440, 880!

>>> fmap standardIntonation [c..c']
[Hertz {getHertz = 440.9438743126817},Hertz {getHertz = 441.0},Hertz {getHertz = 441.0},Hertz {getHertz = 440.9438743126817},Hertz {getHertz = 440.9438743126817},Hertz {getHertz = 441.0},Hertz {getHertz = 441.0},Hertz {getHertz = 440.9438743126817}]
```

**Comment by ejlilley** [comment]
Made a pull request to fix this. Reintroduced Double as the Diff type for Hertz. Also, the IsInterval instance for Double has been moved to Intonation.hs (this is not strictly necessary, it's just for consistency with Hertz/Hertz = Double). I'm still not convinced that IntervalL is necessary -- surely Interval (a,d) is good enough?

**Comment by hanshoglund** [comment]
Fine, merged.

I'm all for removing IntervalL et al but it is non-trivial because of dependencies. Essentially, music-pitch-literal exists so that other packages can use the literals without pulling in western pitch, which is probably a bad idea, seeing as these names represent Western pitch conventions anyway – I hope to fix this eventually, tracking issue here: https://github.com/music-suite/music-pitch-literal/issues/5.
