### ISSUE TITLE
Is `interval` actually an Iso?

### ISSUE THREAD

**Issue by meditans** [music-suite/music-pitch#46]
in the module Music.Pitch.Common.Interval, we have:

> interval :: Iso' (Quality, Number) Interval

which causes the ungraceful failure in

> (Minor, 5) ^. interval
> **\* Exception: qualityToDiff: Unknown interval expression (PerfectType, Minor)

As a philosophical question, are the two types actually isomorphic? Would it be better to have another type of optics instead?

**Comment by hanshoglund** [comment]
This has been fixed in the new monorepo: music-suite/music-suite. Closing this :)
